name: ci

on: [push, pull_request]

jobs:
  test:
    name: deno test
    runs-on: ubuntu-latest
    container: "hayd/debian-deno:1.0.1"
    steps:
      - run: deno --version && ls -a && pwd
      - run: deno test
